### PR TITLE
continuous integration

### PR DESCRIPTION
**Pull request by rydrman**

### CODE REVIEW

**Comment by seanhagen** [comment]
I don't like the idea of having empty tests -- tests should be there to test things. If we're under the coverage target that's okay, it's something to fix.

**Comment by rydrman** [comment]
we'll need to work on writing more test for this but it's working at least. The hound doesn't seem to work on the multiple package thing but we'll leave it running and see if it ever catches anything

**Comment by rydrman** [comment]
if there are no tests in the packages then the coverage is wrong, the empty tests are to make sure that the 0% coverage is taken into account

**Comment by seanhagen** [comment]
Ahhh, that makes more sense.

**Comment by seanhagen** [comment]
Of course, the solution is that we should be writing tests right away :stuck_out_tongue_closed_eyes:

**Comment by rydrman** [comment]
ya feel free to do that ;) I'm not clear on all the stuff in there so I didn't want to take up all that time learning in this PR

**Pull request merged**
